// Repository layer. All case-scoped reads/writes pass through here so the
// authorization rule (a user reaches a case only via family membership) lives in
// one place. API routes must call assertCaseAccess before returning case data.
//
// Backed by Neon (serverless Postgres) via the SQL client in ./client. Every
// function is async. Booleans are stored as integer 0/1 and ISO timestamps as text,
// matching the interface types below.
import "server-only";
import { sql, newId, nowIso } from "./client";

export interface User {
  id: string;
  email: string | null;
  display_name: string;
  is_demo: number;
  created_at: string;
}

export interface CaseRow {
  id: string;
  family_id: string;
  created_by: string;
  title: string;
  status: string;
  questionnaire_version: string | null;
  answer_version: string | null;
  created_at: string;
  updated_at: string;
}

export interface Deceased {
  id: string;
  case_id: string;
  full_name: string | null;
  residence_state: string | null;
  residence_district: string | null;
  death_state: string | null;
  death_district: string | null;
  death_date: string | null;
  death_registered: string | null;
  death_certificate: string | null;
  will_status: string | null;
  certificate_copies: string | null;
  will_registered: string | null;
  executor_present: string | null;
  probate_status: string | null;
  dispute_status: string | null;
  applicant_relationship: string | null;
  nri_status: string | null;
  answers_json: string | null;
  questionnaire_version: string | null;
  updated_at: string;
}

export interface Asset {
  id: string;
  case_id: string;
  asset_type: string;
  service: string;
  label: string | null;
  institution: string | null;
  nominee_status: string | null;
  holding_mode: string | null;
  record_type: string | null;
  authority: string | null;
  scheme: string | null;
  institution_id: string | null;
  details_json: string | null;
  created_at: string;
}

export interface AssetLocation {
  id: string;
  asset_id: string;
  state_code: string | null;
  district: string | null;
  municipality: string | null;
  tehsil_taluk: string | null;
  village_ward: string | null;
  property_identifier: string | null;
  created_at: string;
}

export interface RoadmapStep {
  id: string;
  case_id: string;
  asset_id: string | null;
  procedure_id: string | null;
  service: string;
  title: string;
  requirement: string;
  engine_status: string;
  completeness: string;
  execution_available: number;
  derived_done: number;
  payload: string;
  user_status: string;
  submitted_at: string | null;
  office: string | null;
  ack_number: string | null;
  method: string | null;
  follow_up_date: string | null;
  notes: string | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

/** Fields generated by the engine (not user-set). Tracking + user_status are
 *  preserved across regeneration and are therefore not part of this. */
export type GeneratedRoadmapStep = Omit<
  RoadmapStep,
  | "id"
  | "case_id"
  | "created_at"
  | "updated_at"
  | "user_status"
  | "submitted_at"
  | "office"
  | "ack_number"
  | "method"
  | "follow_up_date"
  | "notes"
>;

// ---- Users & sessions -------------------------------------------------------

export async function createUser(input: {
  displayName: string;
  email?: string | null;
  isDemo?: boolean;
  authMethod?: string;
}): Promise<User> {
  const id = newId("usr");
  const rows = await sql()`
    INSERT INTO users (id, email, display_name, is_demo, auth_method, created_at)
    VALUES (${id}, ${input.email ?? null}, ${input.displayName}, ${input.isDemo === false ? 0 : 1}, ${input.authMethod ?? "demo"}, ${nowIso()})
    RETURNING *`;
  return rows[0] as User;
}

// ---- Jurisdictions (dependent location dropdowns) ---------------------------

export interface Jurisdiction {
  code: string;
  level: string;
  parent_code: string | null;
  name: string;
  name_local: string | null;
  source: string | null;
  lgd_code?: string | null;
  active?: number;
}

export async function listChildJurisdictions(parentCode: string, level: string): Promise<Jurisdiction[]> {
  const rows = await sql()`
    SELECT code, level, parent_code, name, name_local, source, lgd_code, active FROM jurisdictions
    WHERE parent_code = ${parentCode} AND level = ${level} AND active = 1 ORDER BY name`;
  return rows as Jurisdiction[];
}

const normJur = (s: string): string =>
  s.normalize("NFKC").toLowerCase().replace(/&/g, " and ").replace(/[^a-z0-9]+/g, " ").trim().replace(/\s+/g, " ");

/** Searchable dependent selector: children of `parentCode` at `level`, matched by
 *  current name OR any historical/alternate alias (e.g. "Allahabad" -> Prayagraj).
 *  A blank query returns the full child list. LGD codes are the stored keys. */
export async function searchJurisdictions(
  parentCode: string,
  level: string,
  query?: string,
): Promise<Jurisdiction[]> {
  if (!query || !query.trim()) return listChildJurisdictions(parentCode, level);
  const like = `%${normJur(query)}%`;
  const rows = await sql()`
    SELECT DISTINCT j.code, j.level, j.parent_code, j.name, j.name_local, j.source, j.lgd_code, j.active
    FROM jurisdictions j
    LEFT JOIN jurisdiction_aliases a ON a.jurisdiction_code = j.code
    WHERE j.parent_code = ${parentCode} AND j.level = ${level} AND j.active = 1
      AND (
        translate(lower(j.name), '.-_()', '     ') LIKE ${like} OR
        a.alias_norm LIKE ${like}
      )
    ORDER BY j.name`;
  return rows as Jurisdiction[];
}

/** Resolve a stored jurisdiction code to its current official display name.
 *  Case/asset records store codes; this turns a code back into a name for display. */
export async function getJurisdiction(code: string): Promise<Jurisdiction | null> {
  const rows = await sql()`
    SELECT code, level, parent_code, name, name_local, source, lgd_code, active
    FROM jurisdictions WHERE code = ${code}`;
  return (rows[0] as Jurisdiction) ?? null;
}

// ---- Institutions (database-backed selectors) -------------------------------

export interface Institution {
  id: string;
  category: string;
  legal_name: string;
  short_name: string | null;
  regulator: string;
  active: number;
  source: string;
  has_verified_pack?: boolean;
}

/** Searchable institution selector: matches legal name, short name, or any alias,
 *  filtered by category, active only. Values are stable institution ids. */
export async function searchInstitutions(
  category: string | null,
  query: string | undefined,
  limit = 25,
): Promise<Institution[]> {
  const like = query && query.trim() ? `%${normJur(query)}%` : null;
  const rows = await sql()`
    SELECT DISTINCT i.id, i.category, i.legal_name, i.short_name, i.regulator, i.active, i.source
    FROM institutions i
    LEFT JOIN institution_aliases a ON a.institution_id = i.id
    WHERE i.active = 1
      AND (${category}::text IS NULL OR i.category = ${category})
      AND (
        ${like}::text IS NULL
        OR translate(lower(i.legal_name), '.-_()', '     ') LIKE ${like}
        OR translate(lower(coalesce(i.short_name, '')), '.-_()', '     ') LIKE ${like}
        OR a.alias_norm LIKE ${like}
      )
    ORDER BY i.legal_name
    LIMIT ${limit}`;
  return rows as Institution[];
}

export async function getInstitution(id: string): Promise<Institution | null> {
  const rows = await sql()`SELECT id, category, legal_name, short_name, regulator, active, source
    FROM institutions WHERE id = ${id}`;
  return (rows[0] as Institution) ?? null;
}

/** True only when a VERIFIED claim pack exists for this institution+service.
 *  Existence of the institution alone never makes this true. */
export async function institutionHasVerifiedPack(institutionId: string, service: string): Promise<boolean> {
  const rows = await sql()`SELECT 1 FROM institution_claim_packs
    WHERE institution_id = ${institutionId} AND service = ${service} AND status = 'verified' LIMIT 1`;
  return rows.length > 0;
}

export async function createInstitutionVerificationRequest(input: {
  requestedBy?: string | null;
  caseId?: string | null;
  category?: string | null;
  enteredName: string;
  details?: string | null;
}): Promise<{ id: string }> {
  const id = newId("ivr");
  await sql()`INSERT INTO institution_verification_requests
    (id, requested_by, case_id, category, entered_name, details, status, created_at)
    VALUES (${id}, ${input.requestedBy ?? null}, ${input.caseId ?? null}, ${input.category ?? null}, ${input.enteredName}, ${input.details ?? null}, 'open', ${nowIso()})`;
  return { id };
}

// ---- Aadhaar verification transactions (masked references only) -------------

export interface AadhaarTxn {
  id: string;
  nonce_hash: string;
  provider: string;
  status: string;
  aadhaar_last4: string | null;
  masked_mobile: string | null;
  attempts: number;
  user_id: string | null;
  created_at: string;
  expires_at: string;
}

export async function createAadhaarTxn(input: {
  id: string;
  nonceHash: string;
  provider: string;
  last4: string;
  maskedMobile: string;
  ttlMinutes?: number;
}): Promise<void> {
  const now = new Date();
  const expires = new Date(now.getTime() + (input.ttlMinutes ?? 10) * 60_000);
  await sql()`
    INSERT INTO aadhaar_verifications
      (id, nonce_hash, provider, status, aadhaar_last4, masked_mobile, attempts, created_at, expires_at)
    VALUES (${input.id}, ${input.nonceHash}, ${input.provider}, 'otp_sent', ${input.last4}, ${input.maskedMobile}, 0, ${now.toISOString()}, ${expires.toISOString()})`;
}

export async function getAadhaarTxn(id: string): Promise<AadhaarTxn | null> {
  const rows = await sql()`SELECT * FROM aadhaar_verifications WHERE id = ${id}`;
  return (rows[0] as AadhaarTxn) ?? null;
}

export async function bumpAadhaarAttempts(id: string): Promise<number> {
  const rows = await sql()`
    UPDATE aadhaar_verifications SET attempts = attempts + 1 WHERE id = ${id} RETURNING attempts`;
  return (rows[0] as { attempts: number }).attempts;
}

export async function setAadhaarStatus(id: string, status: string, userId?: string): Promise<void> {
  await sql()`
    UPDATE aadhaar_verifications SET status = ${status}, user_id = COALESCE(${userId ?? null}, user_id) WHERE id = ${id}`;
}

export async function getUserById(id: string): Promise<User | null> {
  const rows = await sql()`SELECT * FROM users WHERE id = ${id}`;
  return (rows[0] as User) ?? null;
}

export async function createSession(userId: string, ttlHours = 24 * 14): Promise<string> {
  const id = newId("ses");
  const now = new Date();
  const expires = new Date(now.getTime() + ttlHours * 3600_000);
  await sql()`
    INSERT INTO sessions (id, user_id, created_at, expires_at)
    VALUES (${id}, ${userId}, ${now.toISOString()}, ${expires.toISOString()})`;
  return id;
}

export async function getSessionUser(sessionId: string): Promise<User | null> {
  const rows = await sql()`SELECT user_id, expires_at FROM sessions WHERE id = ${sessionId}`;
  const row = rows[0] as { user_id: string; expires_at: string } | undefined;
  if (!row) return null;
  if (new Date(row.expires_at).getTime() < Date.now()) {
    await sql()`DELETE FROM sessions WHERE id = ${sessionId}`;
    return null;
  }
  return getUserById(row.user_id);
}

export async function deleteSession(sessionId: string): Promise<void> {
  await sql()`DELETE FROM sessions WHERE id = ${sessionId}`;
}

// ---- Preferences & consent --------------------------------------------------

export async function setLanguagePreference(
  userId: string,
  pref: { ui_language?: string; voice_enabled?: boolean; low_bandwidth?: boolean },
): Promise<void> {
  await sql()`
    INSERT INTO language_preferences (user_id, ui_language, voice_enabled, low_bandwidth, updated_at)
    VALUES (${userId}, ${pref.ui_language ?? "en"}, ${pref.voice_enabled ? 1 : 0}, ${pref.low_bandwidth ? 1 : 0}, ${nowIso()})
    ON CONFLICT (user_id) DO UPDATE SET
      ui_language = excluded.ui_language,
      voice_enabled = excluded.voice_enabled,
      low_bandwidth = excluded.low_bandwidth,
      updated_at = excluded.updated_at`;
}

export async function getLanguagePreference(
  userId: string,
): Promise<{ ui_language: string; voice_enabled: number; low_bandwidth: number } | null> {
  const rows = await sql()`
    SELECT ui_language, voice_enabled, low_bandwidth FROM language_preferences WHERE user_id = ${userId}`;
  return (rows[0] as { ui_language: string; voice_enabled: number; low_bandwidth: number }) ?? null;
}

export async function recordConsent(userId: string, kind: string, granted: boolean): Promise<void> {
  await sql()`
    INSERT INTO consents (id, user_id, kind, granted, recorded_at)
    VALUES (${newId("con")}, ${userId}, ${kind}, ${granted ? 1 : 0}, ${nowIso()})`;
}

// ---- Authorization ----------------------------------------------------------

/** True only if the user is a member of the family that owns the case. */
export async function userCanAccessCase(userId: string, caseId: string): Promise<boolean> {
  const rows = await sql()`
    SELECT 1 FROM cases c
    JOIN family_members fm ON fm.family_id = c.family_id
    WHERE c.id = ${caseId} AND fm.user_id = ${userId} LIMIT 1`;
  return rows.length > 0;
}

export class AccessError extends Error {}

export async function assertCaseAccess(userId: string, caseId: string): Promise<void> {
  if (!(await userCanAccessCase(userId, caseId))) {
    throw new AccessError("Not authorized for this case.");
  }
}

// ---- Cases ------------------------------------------------------------------

export async function createCaseForUser(userId: string, title: string): Promise<CaseRow> {
  const now = nowIso();
  const familyId = newId("fam");
  const caseId = newId("case");
  await sql()`INSERT INTO families (id, name, created_by, created_at) VALUES (${familyId}, ${title}, ${userId}, ${now})`;
  await sql()`
    INSERT INTO family_members (id, family_id, user_id, role, permissions, invited_by, created_at)
    VALUES (${newId("mem")}, ${familyId}, ${userId}, 'coordinator', 'full', NULL, ${now})`;
  const rows = await sql()`
    INSERT INTO cases (id, family_id, created_by, title, status, created_at, updated_at)
    VALUES (${caseId}, ${familyId}, ${userId}, ${title}, 'intake', ${now}, ${now})
    RETURNING *`;
  await sql()`INSERT INTO deceased_persons (id, case_id, updated_at) VALUES (${newId("dec")}, ${caseId}, ${now})`;
  await audit(userId, caseId, "case.created", title);
  return rows[0] as CaseRow;
}

export async function getCase(caseId: string): Promise<CaseRow | null> {
  const rows = await sql()`SELECT * FROM cases WHERE id = ${caseId}`;
  return (rows[0] as CaseRow) ?? null;
}

export async function listCasesForUser(userId: string): Promise<CaseRow[]> {
  const rows = await sql()`
    SELECT c.* FROM cases c
    JOIN family_members fm ON fm.family_id = c.family_id
    WHERE fm.user_id = ${userId} ORDER BY c.updated_at DESC`;
  return rows as CaseRow[];
}

export async function touchCase(caseId: string): Promise<void> {
  await sql()`UPDATE cases SET updated_at = ${nowIso()} WHERE id = ${caseId}`;
}

// ---- Deceased / heirs -------------------------------------------------------

export async function getDeceased(caseId: string): Promise<Deceased | null> {
  const rows = await sql()`SELECT * FROM deceased_persons WHERE case_id = ${caseId}`;
  return (rows[0] as Deceased) ?? null;
}

const DECEASED_FIELDS = [
  "full_name",
  "residence_state",
  "residence_district",
  "death_state",
  "death_district",
  "death_date",
  "death_registered",
  "death_certificate",
  "will_status",
  "certificate_copies",
  "will_registered",
  "executor_present",
  "probate_status",
  "dispute_status",
  "applicant_relationship",
  "nri_status",
] as const;

export async function updateDeceased(caseId: string, patch: Partial<Deceased>): Promise<void> {
  const sets: string[] = [];
  const values: unknown[] = [];
  for (const field of DECEASED_FIELDS) {
    if (field in patch) {
      values.push((patch as Record<string, unknown>)[field] ?? null);
      sets.push(`${field} = $${values.length}`);
    }
  }
  if (!sets.length) return;
  values.push(nowIso());
  sets.push(`updated_at = $${values.length}`);
  values.push(caseId);
  await sql().query(
    `UPDATE deceased_persons SET ${sets.join(", ")} WHERE case_id = $${values.length}`,
    values,
  );
  await touchCase(caseId);
}

/** Persist the full schema-driven answer set + the schema version that produced it. */
export async function saveQuestionnaireAnswers(
  caseId: string,
  answersJson: string,
  version: string,
): Promise<void> {
  await sql()`UPDATE deceased_persons
    SET answers_json = ${answersJson}, questionnaire_version = ${version}, updated_at = ${nowIso()}
    WHERE case_id = ${caseId}`;
  await touchCase(caseId);
}

export async function addHeir(
  caseId: string,
  input: { full_name?: string; relationship?: string; is_minor?: boolean; is_claimant?: boolean },
): Promise<void> {
  await sql()`
    INSERT INTO heirs (id, case_id, full_name, relationship, is_minor, is_claimant, created_at)
    VALUES (${newId("heir")}, ${caseId}, ${input.full_name ?? null}, ${input.relationship ?? null}, ${input.is_minor ? 1 : 0}, ${input.is_claimant ? 1 : 0}, ${nowIso()})`;
  await touchCase(caseId);
}

export async function listHeirs(caseId: string) {
  return (await sql()`SELECT * FROM heirs WHERE case_id = ${caseId} ORDER BY created_at`) as unknown[];
}

// ---- Assets -----------------------------------------------------------------

export interface AssetInput {
  asset_type: string;
  service: string;
  label?: string;
  institution?: string;
  institution_id?: string;
  nominee_status?: string;
  holding_mode?: string;
  record_type?: string;
  authority?: string;
  scheme?: string;
  details_json?: string;
  location?: Partial<Omit<AssetLocation, "id" | "asset_id" | "created_at">>;
}

export async function addAsset(caseId: string, input: AssetInput): Promise<Asset> {
  const id = newId("ast");
  const now = nowIso();
  const rows = await sql()`
    INSERT INTO assets (id, case_id, asset_type, service, label, institution, institution_id, nominee_status,
      holding_mode, record_type, authority, scheme, details_json, created_at)
    VALUES (${id}, ${caseId}, ${input.asset_type}, ${input.service}, ${input.label ?? null}, ${input.institution ?? null}, ${input.institution_id ?? null}, ${input.nominee_status ?? null}, ${input.holding_mode ?? null}, ${input.record_type ?? null}, ${input.authority ?? null}, ${input.scheme ?? null}, ${input.details_json ?? null}, ${now})
    RETURNING *`;
  if (input.location) {
    const l = input.location;
    await sql()`
      INSERT INTO asset_locations (id, asset_id, state_code, district, municipality,
        tehsil_taluk, village_ward, property_identifier, created_at)
      VALUES (${newId("loc")}, ${id}, ${l.state_code ?? null}, ${l.district ?? null}, ${l.municipality ?? null}, ${l.tehsil_taluk ?? null}, ${l.village_ward ?? null}, ${l.property_identifier ?? null}, ${now})`;
  }
  await touchCase(caseId);
  await audit(null, caseId, "asset.added", `${input.asset_type} (${input.service})`);
  return rows[0] as Asset;
}

export async function listAssets(caseId: string): Promise<(Asset & { location: AssetLocation | null })[]> {
  const assets = (await sql()`SELECT * FROM assets WHERE case_id = ${caseId} ORDER BY created_at`) as Asset[];
  if (assets.length === 0) return [];
  const ids = assets.map((a) => a.id);
  const locs = (await sql()`
    SELECT * FROM asset_locations WHERE asset_id = ANY(${ids}) ORDER BY created_at`) as AssetLocation[];
  const firstByAsset = new Map<string, AssetLocation>();
  for (const l of locs) if (!firstByAsset.has(l.asset_id)) firstByAsset.set(l.asset_id, l);
  return assets.map((a) => ({ ...a, location: firstByAsset.get(a.id) ?? null }));
}

/** Confirm an asset belongs to a case (authorization is checked separately). */
export async function assetInCase(caseId: string, assetId: string): Promise<boolean> {
  const rows = await sql()`SELECT 1 FROM assets WHERE id = ${assetId} AND case_id = ${caseId} LIMIT 1`;
  return rows.length > 0;
}

/** Update an asset + its (single) location. Used by the wizard's edit action. */
export async function updateAsset(assetId: string, input: Partial<AssetInput>): Promise<void> {
  const cols: Record<string, unknown> = {
    label: input.label, institution: input.institution, institution_id: input.institution_id,
    nominee_status: input.nominee_status, holding_mode: input.holding_mode, record_type: input.record_type,
    authority: input.authority, scheme: input.scheme, details_json: input.details_json,
  };
  const sets: string[] = [];
  const values: unknown[] = [];
  for (const [k, v] of Object.entries(cols)) {
    if (v !== undefined) { values.push(v ?? null); sets.push(`${k} = $${values.length}`); }
  }
  if (sets.length) {
    values.push(assetId);
    await sql().query(`UPDATE assets SET ${sets.join(", ")} WHERE id = $${values.length}`, values);
  }
  if (input.location) {
    const l = input.location;
    const existing = await sql()`SELECT id FROM asset_locations WHERE asset_id = ${assetId} LIMIT 1`;
    if (existing.length) {
      await sql()`UPDATE asset_locations SET state_code=${l.state_code ?? null}, district=${l.district ?? null},
        municipality=${l.municipality ?? null}, tehsil_taluk=${l.tehsil_taluk ?? null},
        village_ward=${l.village_ward ?? null}, property_identifier=${l.property_identifier ?? null}
        WHERE asset_id=${assetId}`;
    } else {
      await sql()`INSERT INTO asset_locations (id, asset_id, state_code, district, municipality, tehsil_taluk, village_ward, property_identifier, created_at)
        VALUES (${newId("loc")}, ${assetId}, ${l.state_code ?? null}, ${l.district ?? null}, ${l.municipality ?? null}, ${l.tehsil_taluk ?? null}, ${l.village_ward ?? null}, ${l.property_identifier ?? null}, ${nowIso()})`;
    }
  }
}

export async function removeAsset(caseId: string, assetId: string): Promise<void> {
  await sql()`DELETE FROM assets WHERE id = ${assetId} AND case_id = ${caseId}`;
  await touchCase(caseId);
  await audit(null, caseId, "asset.removed", assetId);
}

// ---- Roadmap ----------------------------------------------------------------

type PreservedStep = Pick<
  RoadmapStep,
  "procedure_id" | "asset_id" | "service" | "user_status" | "submitted_at" | "office" | "ack_number" | "method" | "follow_up_date" | "notes"
>;

export interface CommitRoadmapInput {
  caseId: string;
  steps: GeneratedRoadmapStep[];
  questionnaireVersion: string;
  answerVersion: string;
  schemaJson: string;
  actorUserId: string | null;
  correlationId: string;
  /** Asset ids that belong to this case — used to satisfy the roadmap_steps.asset_id FK. */
  validAssetIds: Set<string>;
}

/**
 * Generate-and-save the whole roadmap in ONE database transaction: it deletes the
 * old steps, inserts the new ones, stamps the case's questionnaire+answer version,
 * records the schema version, and writes one audit row — all atomically, so a
 * partial roadmap can never be left behind. FKs and required fields are validated
 * before the write. Preserves user-set status/tracking across regeneration.
 */
export async function commitRoadmap(input: CommitRoadmapInput): Promise<void> {
  const { caseId, steps, questionnaireVersion, answerVersion, schemaJson, actorUserId, correlationId, validAssetIds } = input;
  const now = nowIso();
  const q = sql();

  // Validate every node against the schema's required fields and the asset FK BEFORE
  // opening the transaction, so a bad node fails loudly instead of half-writing.
  for (const [i, s] of steps.entries()) {
    if (!s.service || !s.title || !s.requirement || !s.engine_status || !s.completeness || s.payload == null) {
      throw new Error(`Roadmap node ${i} is missing a required field (service/title/requirement/engine_status/completeness/payload).`);
    }
    if (s.asset_id !== null && !validAssetIds.has(s.asset_id)) {
      throw new Error(`Roadmap node ${i} references asset ${s.asset_id}, which is not in case ${caseId}.`);
    }
  }

  // Preserve user-set status AND tracking across regeneration (key: procedure+asset+service).
  const prior = (await q`
    SELECT procedure_id, asset_id, service, user_status, submitted_at, office, ack_number, method, follow_up_date, notes
    FROM roadmap_steps WHERE case_id = ${caseId}`) as PreservedStep[];
  const keyOf = (p: string | null, a: string | null, s: string) => `${p}|${a}|${s}`;
  const priorMap = new Map(prior.map((r) => [keyOf(r.procedure_id, r.asset_id, r.service), r]));

  // One atomic transaction: replace steps + stamp version + record schema + audit.
  const queries = [q`DELETE FROM roadmap_steps WHERE case_id = ${caseId}`];
  steps.forEach((s, i) => {
    const p = priorMap.get(keyOf(s.procedure_id, s.asset_id, s.service));
    queries.push(q`
      INSERT INTO roadmap_steps (id, case_id, asset_id, procedure_id, service, title, requirement,
        engine_status, completeness, execution_available, derived_done, payload, user_status,
        submitted_at, office, ack_number, method, follow_up_date, notes, sort_order, created_at, updated_at)
      VALUES (${newId("stp")}, ${caseId}, ${s.asset_id}, ${s.procedure_id}, ${s.service}, ${s.title}, ${s.requirement},
        ${s.engine_status}, ${s.completeness}, ${s.execution_available}, ${s.derived_done}, ${s.payload}, ${p?.user_status ?? "not_started"},
        ${p?.submitted_at ?? null}, ${p?.office ?? null}, ${p?.ack_number ?? null}, ${p?.method ?? null}, ${p?.follow_up_date ?? null}, ${p?.notes ?? null}, ${s.sort_order ?? i}, ${now}, ${now})`);
  });
  queries.push(q`UPDATE cases SET questionnaire_version = ${questionnaireVersion}, answer_version = ${answerVersion}, updated_at = ${now} WHERE id = ${caseId}`);
  queries.push(q`INSERT INTO questionnaire_schemas (version, schema_json, created_at) VALUES (${questionnaireVersion}, ${schemaJson}, ${now}) ON CONFLICT (version) DO NOTHING`);
  queries.push(q`INSERT INTO audit_events (id, actor_user_id, case_id, action, detail, created_at)
    VALUES (${newId("aud")}, ${actorUserId}, ${caseId}, 'roadmap.regenerated', ${`${steps.length} steps; answer_version=${answerVersion}; cid=${correlationId}`}, ${now})`);

  await q.transaction(queries);
}

const TRACKING_FIELDS = ["submitted_at", "office", "ack_number", "method", "follow_up_date", "notes"] as const;

export async function setStepTracking(
  stepId: string,
  patch: Partial<Pick<RoadmapStep, (typeof TRACKING_FIELDS)[number]>>,
): Promise<void> {
  const sets: string[] = [];
  const values: unknown[] = [];
  for (const f of TRACKING_FIELDS) {
    if (f in patch) {
      values.push((patch as Record<string, unknown>)[f] ?? null);
      sets.push(`${f} = $${values.length}`);
    }
  }
  if (!sets.length) return;
  values.push(nowIso());
  sets.push(`updated_at = $${values.length}`);
  values.push(stepId);
  await sql().query(
    `UPDATE roadmap_steps SET ${sets.join(", ")} WHERE id = $${values.length}`,
    values,
  );
}

/** All steps across the user's cases that have an upcoming/overdue follow-up date. */
export async function listRemindersForUser(userId: string): Promise<Array<RoadmapStep & { case_title: string }>> {
  const rows = await sql()`
    SELECT rs.*, c.title AS case_title FROM roadmap_steps rs
    JOIN cases c ON c.id = rs.case_id
    JOIN family_members fm ON fm.family_id = c.family_id
    WHERE fm.user_id = ${userId} AND rs.follow_up_date IS NOT NULL AND rs.follow_up_date != ''
    ORDER BY rs.follow_up_date ASC`;
  return rows as Array<RoadmapStep & { case_title: string }>;
}

export async function listRoadmap(caseId: string): Promise<RoadmapStep[]> {
  const rows = await sql()`SELECT * FROM roadmap_steps WHERE case_id = ${caseId} ORDER BY sort_order`;
  return rows as RoadmapStep[];
}

export async function getRoadmapStep(stepId: string): Promise<RoadmapStep | null> {
  const rows = await sql()`SELECT * FROM roadmap_steps WHERE id = ${stepId}`;
  return (rows[0] as RoadmapStep) ?? null;
}

export async function setStepUserStatus(stepId: string, status: string): Promise<void> {
  await sql()`UPDATE roadmap_steps SET user_status = ${status}, updated_at = ${nowIso()} WHERE id = ${stepId}`;
}

// ---- Translation cache ------------------------------------------------------

export async function getCachedTranslations(
  locale: string,
  version: string,
  hashes: string[],
): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  if (!hashes.length) return out;
  const rows = (await sql()`
    SELECT source_hash, translated FROM translations
    WHERE locale = ${locale} AND version = ${version} AND source_hash = ANY(${hashes})`) as {
    source_hash: string;
    translated: string;
  }[];
  for (const r of rows) out.set(r.source_hash, r.translated);
  return out;
}

export async function putCachedTranslations(
  locale: string,
  version: string,
  entries: { hash: string; translated: string }[],
): Promise<void> {
  if (!entries.length) return;
  const now = nowIso();
  const q = sql();
  const queries = entries.map(
    (e) => q`
      INSERT INTO translations (id, locale, version, source_hash, translated, created_at)
      VALUES (${`${locale}:${version}:${e.hash}`}, ${locale}, ${version}, ${e.hash}, ${e.translated}, ${now})
      ON CONFLICT (id) DO UPDATE SET translated = excluded.translated, created_at = excluded.created_at`,
  );
  await q.transaction(queries);
}

// ---- Documents (private vault) ----------------------------------------------

export interface DocumentRow {
  id: string;
  case_id: string;
  uploaded_by: string | null;
  label: string | null;
  original_name: string | null;
  mime: string;
  size: number;
  ext: string;
  scan_status: string;
  created_at: string;
}

export async function addDocument(input: {
  id: string;
  caseId: string;
  uploadedBy: string | null;
  label: string | null;
  originalName: string | null;
  mime: string;
  size: number;
  ext: string;
}): Promise<void> {
  await sql()`
    INSERT INTO documents (id, case_id, uploaded_by, label, original_name, mime, size, ext, scan_status, created_at)
    VALUES (${input.id}, ${input.caseId}, ${input.uploadedBy}, ${input.label}, ${input.originalName}, ${input.mime}, ${input.size}, ${input.ext}, 'not_scanned', ${nowIso()})`;
  await touchCase(input.caseId);
  await audit(input.uploadedBy, input.caseId, "document.uploaded", input.label ?? input.originalName ?? input.id);
}

export async function listDocuments(caseId: string): Promise<DocumentRow[]> {
  const rows = await sql()`SELECT * FROM documents WHERE case_id = ${caseId} ORDER BY created_at DESC`;
  return rows as DocumentRow[];
}

export async function getDocument(docId: string): Promise<DocumentRow | null> {
  const rows = await sql()`SELECT * FROM documents WHERE id = ${docId}`;
  return (rows[0] as DocumentRow) ?? null;
}

export async function deleteDocumentRow(docId: string): Promise<void> {
  await sql()`DELETE FROM documents WHERE id = ${docId}`;
}

// ---- Audit ------------------------------------------------------------------

export async function audit(
  actorUserId: string | null,
  caseId: string | null,
  action: string,
  detail?: string,
): Promise<void> {
  await sql()`
    INSERT INTO audit_events (id, actor_user_id, case_id, action, detail, created_at)
    VALUES (${newId("aud")}, ${actorUserId}, ${caseId}, ${action}, ${detail ?? null}, ${nowIso()})`;
}
